---
title: "pre-process-review"
author: "Wanhe Zhao"
date: "4/12/2019"
output: html_document
---

```{r}
review <- read.csv("review.csv")
price <- read.csv("price.csv")
```

```{r}
colnames(review)
```

```{r}
colnames(price)
df <- merge(price,review,by="id")
```

```{r}
# this is a n>p question.
dim(price)
dim(review)
dim(df)
```









```{r}
boxplot(price$price, ylab="price")
```


# Preprocess price
```{r}
price <- read.csv("price.csv")
price <- price[price$price!=0,]
price <- price[price$price!=max(price$price),]
price <- price[price$id != 935671,]
#remove four rows

price <- mutate(price, 
            #host_is_superhost = ifelse(`host_is_superhost` == "f", 0, 1),
            #host_identity_verified = ifelse(`host_identity_verified` == "f",0, 1),
            In_Downtown = ifelse(`neighbourhood_group_cleansed` =="Downtown", 1, 0),
            In_Delridge = ifelse(`neighbourhood_group_cleansed`=="Delridge", 1, 0),
            In_Lake_City = ifelse(`neighbourhood_group_cleansed`=="Lake City", 1,0))



num_amenities <- numeric(0)
for (i in 1:range(nrow(price))){
   num_amenities[i]<-length(strsplit(as.character(price$amenities[i]), ",")[[1]])
}
price$num_amenities <- num_amenities


```

```{r}
#change property type
ggplot(data = price, aes(x = factor(property_type), y = price)) + geom_boxplot() + labs(x = "property_type", y="price") + ylim(0, 600)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
prop_type <- c("Apartment", "Condominium", "Guesthouse", "House", "Townhouse", "Serviced apartment", "Guest suite")
levels(price$property_type)[!(levels(price$property_type) %in% prop_type)] <- rep("Other", times=20)
ggplot(data = price, aes(x = factor(property_type), y = price)) + geom_boxplot() + labs(x = "property_type", y="price") + ylim(0, 600)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


# Popular_Landmarks

```{r}
library(geosphere)
add_pop <- function(yourData){
  Museum_of_Pop_Culture <- c(-122.3481, 47.6215) #long, lati
  Pike_Place_Market <- c(-122.3422, 47.6097)
  Olympic_Sculpture_Park <- c(-122.3553, 47.6166)
  Seattle_Great_Wheel <- c(-122.3425, 47.6062)
  Seattle_Art_Museum <- c(-122.3381, 47.6073)
  Kerry_Park <-c(-122.3599, 47.6295)
  meter_to_mile = 0.000621371
  total_nearby_landmarks <- (ifelse(distm(Museum_of_Pop_Culture, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0) + ifelse(distm(Pike_Place_Market, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0)
  + ifelse(distm(Olympic_Sculpture_Park, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0)
  + ifelse(distm(Seattle_Great_Wheel, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0)
  + ifelse(distm(Seattle_Art_Museum, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0)
  + ifelse(distm(Kerry_Park, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0))
  return(total_nearby_landmarks)
}

yourData <-cbind(review$longitude, review$latitude)
total_nearby_landmarks_review <- add_pop(yourData)
review$total_nearby_landmarks <- total_nearby_landmarks_review[1,]
yourData_price <-cbind(price$longitude, price$latitude)
total_nearby_landmarks_price<- add_pop(yourData_price)
price$total_nearby_landmarks <- total_nearby_landmarks_price[1,]
#change couch in bed_type to real_bed
levels(price$bed_type)[(levels(price$bed_type) == "Couch")] <- "Real Bed"
```

# Split Train and Validation set before EDA(with response)
```{r}
set.seed(1)
n_val <- floor(0.2*nrow(price))
n_train <- nrow(price) - n_val
idx <- sample(1:nrow(price), n_train, replace=FALSE)
price_train <- price[idx,]
price_val <- price[-idx,]
```


```{r}
library(gridExtra)

 ggplot(data = price_train, aes(x = factor(room_type), y = price)) + geom_boxplot() + labs(x = "room_type", y="price") + ylim(0, 500)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggplot(data = price_train, aes(x = factor(bed_type), y = price)) + geom_boxplot() + labs(x = "bed_type", y="price") + ylim(0, 500)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(data = price_train, aes(x = factor(bed_type), y = price)) + geom_boxplot() + labs(x = "bed_type", y="price") + ylim(0, 500)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggplot(data = price_train, aes(x = factor(instant_bookable), y = price)) + geom_boxplot() + labs(x = "instant_bookable", y="price") + ylim(0, 500)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggplot(data = price_train, aes(x = factor(cancellation_policy), y = price)) + geom_boxplot() + labs(x = "cancellation_policy", y="price") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

```{r}
colnames(price_val)
```


```{r}

price_train <- price_train[,-c(9,12,13,19)]
write.csv(price_train, "price_train.csv", row.names = FALSE)
price_val <- price_val[,-c(9,12,13,19)]
write.csv(price_val, "price_val.csv", row.names = FALSE)
```


```{r}
ggplot(data = price_train, aes(x = factor(total_nearby_landmarks), y = price)) + geom_boxplot() + labs(x = "total_nearby_landmarks", y="price") + ylim(0, 500)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
# base line lm
base_model <- lm(price ~ . , data= price_train[, -c(1,2)])
mean((base_model$fit - price_train$price)^2)
mean((predict(base_model,price_val[, -c(1,2)]) - price_val$price)^2)
```





```{r}
#train & val
x_train <- model.matrix(~.,price_train[, -c(1,2, 21)])
MSE_val <- numeric(0)
MSE_train <- numeric(0)
lambda_min <- numeric(0)
x_val <- model.matrix(~.,price_val[, -c(1,2,21)])
for (i in 1:11){
  model1 <- cv.glmnet(y=price_train$price, x=x_train, alpha = seq(0,1,by = 0.1)[i],family="gaussian")
  lambda_min[i] <- model1$lambda.min
  MSE_train[i] = mean((predict(model1, s = model1$lambda.min, newx=x_train)-price_train$price)^2)
  MSE_val[i] = mean((predict(model1, s = model1$lambda.min, newx=x_val) - price_val$price)^2) 
}


```

```{r}

plot(seq(0,1,by = 0.1), MSE_train, ylim=c(min(MSE_train), max(MSE_val)), type = "o")
lines(seq(0,1,by = 0.1), MSE_val, type = "o")
```


```{r}
#test set
price_test <- read.csv("price_test_clean.csv")
model_select <- glmnet(y=price_train$price, x= x_train, alpha = 0, lambda = lambda_min[1], family="gaussian")

x_test <- model.matrix(~.,price_test[, -c(1,2,21)])

mean((predict(model_select, x_test) - price_test$price)^2)
```









