---
title: "manipulate_test"
author: "Wanhe Zhao"
date: "4/22/2019"
output: html_document
---
```{r}
price <- read.csv("price_test.csv")
```

```{r}
price_clean <- read.csv("price_test_clean.csv")
colnames(price_clean)
```



```{r}
price <- mutate(price, 
            #host_is_superhost = ifelse(`host_is_superhost` == "f", 0, 1),
            #host_identity_verified = ifelse(`host_identity_verified` == "f",0, 1),
            In_Downtown = ifelse(`neighbourhood_group_cleansed` =="Downtown", 1, 0),
            In_Delridge = ifelse(`neighbourhood_group_cleansed`=="Delridge", 1, 0),
            In_Lake_City = ifelse(`neighbourhood_group_cleansed`=="Lake City", 1,0))



num_amenities <- numeric(0)
for (i in 1:range(nrow(price))){
   num_amenities[i]<-length(strsplit(as.character(price$amenities[i]), ",")[[1]])
}
price$num_amenities <- num_amenities

prop_type <- c("Apartment", "Condominium", "Guesthouse", "House", "Townhouse", "Serviced apartment", "Guest suite")
levels(price$property_type)[!(levels(price$property_type) %in% prop_type)] <- rep("Other", times=20)

library(geosphere)
add_pop <- function(yourData){
  Museum_of_Pop_Culture <- c(-122.3481, 47.6215) #long, lati
  Pike_Place_Market <- c(-122.3422, 47.6097)
  Olympic_Sculpture_Park <- c(-122.3553, 47.6166)
  Seattle_Great_Wheel <- c(-122.3425, 47.6062)
  Seattle_Art_Museum <- c(-122.3381, 47.6073)
  Kerry_Park <-c(-122.3599, 47.6295)
  meter_to_mile = 0.000621371
  total_nearby_landmarks <- (ifelse(distm(Museum_of_Pop_Culture, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0) + ifelse(distm(Pike_Place_Market, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0)
  + ifelse(distm(Olympic_Sculpture_Park, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0)
  + ifelse(distm(Seattle_Great_Wheel, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0)
  + ifelse(distm(Seattle_Art_Museum, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0)
  + ifelse(distm(Kerry_Park, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0))
  return(total_nearby_landmarks)
}

yourData <-cbind(review$longitude, review$latitude)
total_nearby_landmarks_review <- add_pop(yourData)
yourData_price <-cbind(price$longitude, price$latitude)
total_nearby_landmarks_price<- add_pop(yourData_price)
price$total_nearby_landmarks <- total_nearby_landmarks_price[1,]
```

```{r}
dim(price)
```
```{r}
price[,c(9,12,13,19)]
```

```{r}
price <- price[,-c(9,12,13,19)]
write.csv(price, "price_test_clean.csv", row.names = FALSE)
```

```{r}
price_test <- read.csv("price_test_clean.csv")
colnames(price_test)
```




