---
title: "preprocess_reviewtest"
author: "Wanhe Zhao"
date: "4/26/2019"
output: html_document
---

```{r}
review <- read.csv("review_test.csv")
head(review)
```

```{r}
# remove price is zero case
review = review[review$price != 0, ]

```

```{r message=FALSE, warning=FALSE}
library(dplyr)

num_amenities <- numeric(0)
for (i in 1:range(nrow(review))){
   num_amenities[i]<-length(strsplit(as.character(review$amenities[i]), ",")[[1]])
}
review$num_amenities <- num_amenities
```

```{r}
#unbalanced set
mean(review$review_scores_rating)
```

```{r}
library(dplyr)
library(reshape2)
library(ggplot2)


levels(review$property_type)[!(levels(review$property_type) %in% prop_type)] <- rep("Other", times=24)
df_heatmap <- melt(table(review$property_type, review$review_scores_rating))

ggplot(data = df_heatmap, aes(x = Var1, y = factor(Var2))) + scale_fill_gradient(low = "white", high = "steelblue") + labs(x = "property_type", y="review") +
  geom_tile(aes(fill = value), color = "white") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
library(geosphere)
add_pop <- function(yourData){
  Museum_of_Pop_Culture <- c(-122.3481, 47.6215) #long, lati
  Pike_Place_Market <- c(-122.3422, 47.6097)
  Olympic_Sculpture_Park <- c(-122.3553, 47.6166)
  Seattle_Great_Wheel <- c(-122.3425, 47.6062)
  Seattle_Art_Museum <- c(-122.3381, 47.6073)
  Kerry_Park <-c(-122.3599, 47.6295)
  meter_to_mile = 0.000621371
  total_nearby_landmarks <- (ifelse(distm(Museum_of_Pop_Culture, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0) + ifelse(distm(Pike_Place_Market, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0)
  + ifelse(distm(Olympic_Sculpture_Park, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0)
  + ifelse(distm(Seattle_Great_Wheel, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0)
  + ifelse(distm(Seattle_Art_Museum, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0)
  + ifelse(distm(Kerry_Park, yourData, fun = distHaversine)*meter_to_mile <1, 1, 0))
  return(total_nearby_landmarks)
}

yourData <-cbind(review$longitude, review$latitude)
total_nearby_landmarks_review <- add_pop(yourData)
review$total_nearby_landmarks <- total_nearby_landmarks_review[1,]

```

```{r}
levels(review$bed_type)[(levels(review$bed_type) == "Couch")] <- "Real Bed"
```

```{r}
review <- review[, -23]
```


```{r}
review_test <- review[,-c(1,9,11,12,19)]
write.csv(review_test, "review_test_clean.csv", row.names = FALSE)
```


